HMTF/HMTF/Controllers/AuditTrailController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMTF.Controllers
{
    public class AuditTrailController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HMTF/HMTF/Controllers/ClinicVisitController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMTF.Controllers
{
    public class ClinicVisitController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Coba()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
    }
}

HMTF/HMTF/Controllers/KaryawanController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMTF.Controllers
{
    public class KaryawanController : Controller
    {
        //    private readonly HTMFDbContext dbContext;

        //    public KaryawanController(HTMFDbContext dbContext)
        //    {
        //        this.dbContext = dbContext;
        //    }

        //    [Authorize]
        //    [HttpGet]
        //    public IActionResult Add()
        //    {
        //        return View();
        //    }

        //    [HttpPost]
        //    public async Task<IActionResult> Add(AddUserRequest addUserRequest)
        //    {
        //        var user = new User
        //        {
        //            Name = addUserRequest.Name,
        //            Departement = addUserRequest.Departement,
        //            CreatedBy = addUserRequest.CreatedBy,
        //            CreatedAt = DateTime.Now,
        //        };

        //        await dbContext.Users.AddAsync(user);
        //        await dbContext.SaveChangesAsync();

        //        return RedirectToAction("List", "Karyawan");
        //    }

        //    [HttpGet]
        //    public async Task<IActionResult> List()
        //    {
        //        var user = await dbContext.Users.ToListAsync();

        //        return View(user);
        //    }

        //    [HttpGet]
        //    public async Task<IActionResult> Edit(Guid id)
        //    {
        //        var user = await dbContext.Users.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

        //        if (user == null)
        //        {
        //            return NotFound();
        //        }

        //        return View(user);
        //    }

        //    [HttpPost]
        //    public async Task<IActionResult> Edit(User editUserRequest)
        //    {
        //        var user = await dbContext.Users.FindAsync(editUserRequest.Id);

        //        if (user != null)
        //        {
        //            user.Name = editUserRequest.Name;
        //            user.Departement = editUserRequest.Departement;
        //            user.CreatedBy = editUserRequest.CreatedBy;
        //            user.CreatedAt = editUserRequest.CreatedAt;

        //            await dbContext.SaveChangesAsync();
        //        }

        //        return RedirectToAction("List", "Karyawan");
        //    }

        //    [HttpPost]
        //    public async Task<IActionResult> Delete(User userDelete)
        //    {
        //        var user = await dbContext.Users.AsNoTracking().FirstOrDefaultAsync(x => x.Id == userDelete.Id);

        //        if (user != null)
        //        {
        //            dbContext.Users.Remove(user);
        //            await dbContext.SaveChangesAsync();
        //        }
        //        return RedirectToAction("List", "Karyawan");
        //    }


        public IActionResult List()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Add()
        {
            return View();
        }
    }
}

HMTF/HMTF/Controllers/SpecialMCUController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMTF.Controllers
{
    public class SpecialMCUController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }

    }
}

HMTF/HMTF/Views/Shared/_Footer.cshtml
 <!-- Footer -->
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
        <div class="mb-2 mb-md-0">
        </div>
        <div>
            <a href="https://themeselection.com/" target="_blank" class="footer-link me-4">© Copyright Dankos 2024, Clinic Data Center V01</a>
        </div>
    </div>
</footer>
<!-- / Footer -->

HMTF/HMTF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--added 27/2/24-->
<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/content/assets/"
      data-template="vertical-menu-template-free">
<!--added 27/2/24-->
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!--added 27/2/24-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HMTF.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DataTables/css/dataTables.bootstrap5.css" />

    <!--added 27/2/24-->

    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Sneat - Free Bootstrap 5 HTML Admin Template</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/content/assets/img/favicon/favicon.ico" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/content/assets/vendor/fonts/boxicons.css" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Core CSS -->
    <!--<link rel="stylesheet" href="~/content/assets/vendor/css/core.css" />
    <link rel="stylesheet" href="~/content/assets/vendor/css/theme-default.css" />-->
    <link rel="stylesheet" href="~/content/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/content/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/content/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/content/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <link rel="stylesheet" href="~/content/assets/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->
    <link rel="stylesheet" href="~/content/assets/vendor/css/pages/page-auth.css">
    <link rel="stylesheet" href="~/content/assets/vendor/css/pages/page-misc.css">

    <!--datepivker css-->
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.min.css" />
    <!-- Helpers -->
    <script src="~/content/assets/vendor/js/helpers.js"></script>
    <script src="~/js/jquery-3.7.1.js"></script>

    <!--added 27/2/24-->
    <style type="text/css">
        .layout-menu-fixed .layout-navbar-full .layout-menu,
        .layout-page {
            padding-top: 0px !important;
        }

        .content-wrapper {
            padding-bottom: 0px !important;
        }</style>
    <!--added 27/2/24-->
    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/content/assets/js/config.js"></script>
</head>
<body>

    <div>
        @RenderBody()
    </div>


    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/content/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/content/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/content/assets/vendor/js/bootstrap.js"></script>
    <script src="~/content/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <!--datatables-->
    <script src="~/js/momen.min.js"></script>
    <script src="~/js/dateTime.dataTables.js"></script>
    <script src="~/DataTables/js/dataTables.dataTables.min.js"></script>
    <script src="~/DataTables/js/dataTables.min.js"></script>
    <script src="~/DataTables/js/dataTables.js"></script>
    <script src="~/js/bootsrap-datepicker.min.js"></script>
    <script src="~/js/dataTables.js"></script>
    <script src="~/DataTables/js/dataTables.bootstrap5.js"></script>


    <script src="~/content/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/content/assets/vendor/libs/apex-charts/apexcharts.js"></script>
    <script src="~/Content/assets/vendor/libs/masonry/masonry.js"></script>


    <!-- Main JS -->
    <script src="~/content/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/content/assets/js/dashboards-analytics.js"></script>
    <script src="~/content/assets/js/extended-ui-perfect-scrollbar.js"></script>
    <script src="~/content/assets/js/ui-toasts.js"></script>
    <script src="~/content/assets/js/ui-popover.js"></script>




    <!-- Place this tag in your head or just before your close body tag. -->

    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <script>
        var currentUrl = window.location.pathname;
        $('.menu-link').each(function () {
            var href = $(this).attr('href')
            if (href === currentUrl) {

                // added 27 / 2 / 24
                $(this).closest('.menu-item').addClass('active open'); // + active &openmenu-item
                $(this).closest('.menu-sub').addClass('open show'); // + show di dropdown
                // added 27 / 2 / 24
            }
        });
    </script>

    <!--Modal Profile-->
    <div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="profileModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="profileModal">Profile</h5>
                </div>
                <form>
                    <div class="modal-body">
                        <input type="hidden" name="Id" />
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>

                        </div>
                        <div class="mb-3">
                            <label for="CreatedBy" class="form-label">CreatedBy</label>

                        </div>
                        <div class="mb-3">
                            <label for="department" class="form-label">CreatedAt</label>

                        </div>
                        <div class="mb-3">
                            <label for="department" class="form-label">Department</label>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

HMTF/HMTF/Views/Shared/_Navbar.cshtml
<!--Added 4/3/24, 8.34am-->
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
<!--Added 4/3/24, 8.34am-->

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center">
                <a href="javascript:history.go(-1);" class="text-decoration-none">
                    <i class='bx bx-left-arrow-circle'></i>
                </a>
            </div>
        </div>
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <!-- Place this tag where you want the button to render. -->
            <li class="nav-item lh-1 me-3">
                <span></span>
            </li>
            <li class="navbar-item">
                @if (signInManager.IsSignedIn(User))
                {
                    <div class="flex-grow-0">
                        <span class="fw-semibold d-block">@User?.Identity?.Name</span>
                        <small class="text-muted">Admin</small>
                    </div>
                }
                else
                {
                    <div class="flex-grow-1">
                        <span class="fw-semibold d-block">No user active. </span>
                        <small class="text-muted">-</small>
                    </div>
                }
            </li>
            <li class="navbar-item">
                <a class="nav-link dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                    <i class='bx bxs-bell mx-2'></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#profileModal">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        <img src="~/content/assets/img/avatars/1.png" alt="" class="w-px-40 h-auto rounded-circle">
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#profileModal">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>

            <!--/ User -->
        </ul>
    </div>
</nav>

HMTF/HMTF/Views/Shared/_Sidebar.cshtml
<!-- Menu -->
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="Home" asp-action="Index" class="app-brand-link">
            <span class="app-brand-logo demo">
                <img src="/1200px-Kalbe_Farma.svg-removebg-preview.png" alt=""
                     width="115"
                     viewBox="0 0 115 42" />
                @* <svg width="25"
                     viewBox="0 0 25 42"
                     version="1.1"
                     xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink">
                    <defs>
                        <path d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                              id="path-1"></path>
                        <path d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                              id="path-3"></path>
                        <path d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                              id="path-4"></path>
                        <path d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                              id="path-5"></path>
                    </defs> *@
                    <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                            <g id="Icon" transform="translate(27.000000, 15.000000)">
                                <g id="Mask" transform="translate(0.000000, 8.000000)">
                                    <mask id="mask-2" fill="white">
                                        <use xlink:href="#path-1"></use>
                                    </mask>
                                    <use fill="#696cff" xlink:href="#path-1"></use>
                                    <g id="Path-3" mask="url(#mask-2)">
                                        <use fill="#696cff" xlink:href="#path-3"></use>
                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                                    </g>
                                    <g id="Path-4" mask="url(#mask-2)">
                                        <use fill="#696cff" xlink:href="#path-4"></use>
                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                                    </g>
                                </g>
                                <g id="Triangle"
                                   transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                                    <use fill="#696cff" xlink:href="#path-5"></use>
                                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item mt-5">
            <a href="@Url.Action("Index", "Home")" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>

        <!-- Layouts -->
 

        <li class="menu-header small text-uppercase dropdown">
            <span class="menu-header-text">Master Data </span>
        </li>
        <li class="menu-item">
            <a asp-action="List" asp-controller="Karyawan" class="menu-link">
                <i class='menu-icon bx bx-buildings'></i>
                <div data-i18n="Master">Master </div>
            </a>
        </li>

        <!--Transaction-->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Transaction </span>
        </li>
        <li class="menu-item">
            <a href="#" class="menu-link menu-toggle">
                <i class='menu-icon tf-icons bx bx-detail'></i>
                <div data-i18n="MCU">MCU</div>
            </a>
            <ul class="menu-sub open">
                <li class="menu-item">
                    <a asp-action="Index" asp-controller="FirstMCU" class="menu-link">
                        <i class='menu-bullet menu-bullet-dot'>
                            <span></span>
                        </i>
                        <span data-i18n="MCU Awal">MCU Awal</span>
                    </a>
                </li>
                <li class="menu-item">
                    <a asp-action="Index" asp-controller="SpecialMCU" class="menu-link">
                        <i class='menu-bullet menu-bullet-dot'>
                            <span></span>
                        </i>
                        <span data-i18n="MCU Khusus">MCU Khusus</span>
                    </a>
                </li>
                <li class="menu-item">
                    <a asp-action="Index" asp-controller="PeriodicMCU" class="menu-link">
                        <i class='menu-bullet menu-bullet-dot'>
                            <span></span>
                        </i>
                        <span data-i18n="MCU Berkala">MCU Berkala</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="menu-item">
            <a asp-action="Index" asp-controller="ClinicVisit" class="menu-link">
                <i class='menu-icon bx bx-buildings'></i>
                <div data-i18n="Kunjungan Klinik">Kunjungan Klinik</div>
            </a>
        </li>

        <li class="menu-item">
            <a asp-action="Index" asp-controller="AuditTrail" class="menu-link">
                <i class='menu-icon bx bxs-group'></i>
                <div data-i18n="AuditTrail">Audit Trail</div>
            </a>
        </li>

        
        <!-- MONITORING -->
        <li class="menu-header small text-uppercase"><span class="menu-header-text">Monitoring</span></li>
        <li class="menu-item">
            <a href="https://github.com/themeselection/sneat-html-admin-template-free/issues"
               target="_blank"
               class="menu-link">
                <i class="menu-icon tf-icons bx bx-support"></i>
                <div data-i18n="Support">Support</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="https://themeselection.com/demo/sneat-bootstrap-html-admin-template/documentation/"
               target="_blank"
               class="menu-link">
                <i class="menu-icon tf-icons bx bx-file"></i>
                <div data-i18n="Documentation">Documentation</div>
            </a>
        </li>
    </ul>
</aside>
<!-- / Menu -->