HMTF/HMTF/Models/PeriodicMCU.cs
using System.ComponentModel.DataAnnotations;

namespace HMTF.Models
{
    public class PeriodicMCU
    {
        [Key]
        public int Id { get; set; }

    }
}

HMTF/HMTF/Controllers/PeriodicMCUController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMTF.Controllers
{
    public class PeriodicMCUController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upload()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        public IActionResult SubDetails()
        {
            return View();
        }
    }
}

HMTF/HMTF/Views/PeriodicMCU/Index.cshtml
@{
    ViewData["Title"] = "MCU/MCU Berkala";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            @await Html.PartialAsync("_Sidebar")
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->
                @await Html.PartialAsync("_Navbar")

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->
                    <div class="container-xxl flex-grow-1 container-p-y">
                        <div class="row">
                            <div class="mt-3">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h5 class="m-0 display-6">MCU Berkala</h5>
                                    </div>
                                    <div class="col-auto">
                                        <a class="btn btn-success" href="#" data-bs-toggle="modal" data-bs-target="#exportMCUModal"><i class="menu-icon bx bx-download"></i> Export</a>
                                    </div>
                                    <div class="col-auto">
                                        <a class="btn btn-warning" href="#" data-bs-toggle="modal" data-bs-target="#uploadMCUModal"><i class="menu-icon bx bx-upload"></i> Upload</a>
                                    </div>
                                </div>
                                <!--Modal-->
                                <div class="modal fade" id="uploadMCUModal" tabindex="-1" role="dialog" aria-labelledby="uploadMCUModallLabel" aria-hidden="true">
                                    <div class="modal-dialog d-flex align-items-center" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="uploadMCUModalLabel">Upload MCU</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                            </div>
                                            <form method="POST">
                                                <div class="modal-body">
                                                    <input type="file" class="custom-input m-3" id="file">
                                                    <label for="file" class="custom-upload mx-4 mt-3 align-items-center text-center d-flex justify-content-center">Upload File</label>
                                                </div>
                                                <div class="modal-footer d-flex justify-content-end">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-primary">Upload</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <!--/Modal-->
                                <!--Modal Export-->
                                <div class="modal fade" id="exportMCUModal" tabindex="-1" role="dialog" aria-labelledby="downloadModallLabel" aria-hidden="true">
                                    <div class="modal-dialog d-flex align-items-center" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="downloadModalLabel">Export MCU</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                            </div>
                                            <form method="POST">
                                                <div class="modal-body">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <label class="col-form-label" for="kujunganDari">Date From</label>
                                                            <input type="date" id="kunjunganDari" class="form-control form-control-md" placehoder="Dari" name="dari" />
                                                        </div>
                                                        <div class="col-md-6">
                                                            <label class="col-form-label" for="kunjunganHingga">Date To</label>
                                                            <input type="date" id="kunjunganHingga" class="form-control form-control-md" placehoder="Hingga" name="hingga" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer d-flex justify-content-end">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-primary">Export</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <!--/Modal Export-->
                            </div>

                            <div class="col-lg-12 my-4 order-0">
                                <div class="card">
                                    <div class="d-flex align-items-end row">
                                        <div class="col-sm-12">
                                            <div class="card-body">
                                                <div class="table-responsive text-nowrap" >
                                                    <table class="table table-striped" id="myTable">
                                                        <thead>
                                                            <tr>
                                                                <th>NIK</th>
                                                                <th>Name</th>
                                                                <th>Department</th>
                                                                <th>Status</th>
                                                                <th>Actions</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>0001</td>
                                                                <td>Akmal</td>
                                                                <td>IT</td>
                                                                <td>FIT</td>
                                                                <td><a asp-action="Details" asp-controller="PeriodicMCU">Details</a></td>
                                                            </tr>
                                                            <!---->
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <!-- / Content -->
                                                <div class="content-backdrop fade"></div>
                                            </div>
                                            <!-- Content wrapper -->
                                        </div>
                                        <!-- / Layout page -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                $('#myTable').DataTable({
                });                
            });
        </script>
    </div>

</body>